{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-redcapr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/REDCapR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/REDCapR/REDCapR_{{ version }}.tar.gz
  sha256: b83505d9d81911f1f4f7f777fdc7f03869c0f5cdd4976843d6a14d6ace254e3f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.0
    - r-dplyr >=1.0
    - r-httr >=1.4.0
    - r-jsonlite
    - r-magrittr >=1.5
    - r-readr >=2.0
    - r-rlang >=0.4
    - r-tibble >=2.0
    - r-tidyr >=1.0
  run:
    - r-base
    - r-checkmate >=2.0
    - r-dplyr >=1.0
    - r-httr >=1.4.0
    - r-jsonlite
    - r-magrittr >=1.5
    - r-readr >=2.0
    - r-rlang >=0.4
    - r-tibble >=2.0
    - r-tidyr >=1.0

test:
  commands:
    - $R -e "library('REDCapR')"           # [not win]
    - "\"%R%\" -e \"library('REDCapR')\""  # [win]

about:
  home: https://ouhscbbmc.github.io/REDCapR/, https://github.com/OuhscBbmc/REDCapR, https://www.ouhsc.edu/bbmc/, https://project-redcap.org
  license: MIT
  summary: Encapsulates functions to streamline calls from R to the REDCap API.  REDCap (Research Electronic Data CAPture) is a web application for building and managing online surveys and databases developed at Vanderbilt University.  The Application Programming Interface (API) offers an avenue to access and modify data
    programmatically, improving the capacity for literate and reproducible programming.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
